name: Auto Blog Publisher

on:
  schedule:
    - cron: '0 8 * * *' # Runs daily at 08:00 UTC
  workflow_dispatch:     # Allows manual runs from GitHub UI

jobs:
  run-agent:
    runs-on: ubuntu-latest

    env:
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      BASE_URL: ${{ secrets.BASE_URL }}
      MODEL_ID: ${{ secrets.MODEL_ID }}
      BLOG_PUSH_TOKEN: ${{ secrets.BLOG_PUSH_TOKEN }}
      BLOG_REPO: ${{ secrets.BLOG_REPO }}
      BLOG_BRANCH: ${{ secrets.BLOG_BRANCH }}
      BLOG_POSTS_DIR: ${{ secrets.BLOG_POSTS_DIR }}
      POST_TIME: "08:00"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run blog agent
        run: python agent.py
